"""Centralized error constants (auto-generated).

Values follow the format "[<folder>/<function>] error".
"""

AGENT_BACKGROUND_EVAL = "[agent/_background_eval] error"
AGENT_BUILD_CONTEXT = "[agent_utils/build_context] error"
AGENT_RENDER_PROMPT = "[agent_utils/render_prompt] error"
AGENT_RUN = "[agent/run] error"
AGENT_SANITIZE_INPUT = "[agent_utils/sanitize_input] error"
AGENT_STREAM_CAPTURE = "[agent_utils/stream_with_capture] error"
BUILD_DOC_METADATA = "[eval/build_doc_metadata] error"
COMPUTE_RATING = "[eval/compute_rating] error"
HALLUCINATION_DETECTION = "[eval/detect_hallucination] error"
POSTGRES_INIT_DB = "[postgres/init_db] error"
RUN_MODEL_OUTPUT = "[model/run_model_output] error"
SCORE_GROUNDEDNESS = "[eval/score_groundedness_with_embeddings] error"
SCORE_HELPFULNESS = "[eval/score_helpfulness_with_llm] error"
SESSION_REPO_CREATE_SESSION = "[session_repository/create_session] error"
SESSION_REPO_GET_MESSAGES = "[session_repository/get_messages_for_session] error"
SESSION_REPO_GET_OR_CREATE_SESSION = "[session_repository/get_or_create_session] error"
SESSION_REPO_GET_SESSION_BY_ID = "[session_repository/get_session_by_id] error"
SESSION_REPO_STORE_MESSAGE = "[session_repository/store_message] error"
STREAM_WITH_CLI = "[model/stream_with_cli] error"
STREAM_WITH_HTTP = "[model/stream_with_http] error"
TRACE_SPAN = "[eval/trace_eval_span] error"
VERIFY_PROMPT_VARS = "[model/verify_prompt_variables] error"
VECTOR_REPO_UPSERT = "[pgvector_repository/upsert] error"
VECTOR_REPO_TOPK = "[pgvector_repository/topk] error"
